### ISSUE TITLE
Vertical strips of regions left out on cell segmentation/inference

### ISSUE THREAD

**Issue by Calebium** [TissueImageAnalytics/tiatoolbox#482]
- TIA Toolbox version: 1.2.1
- Python version: 3.7.13
- Operating System: Linux CentOS 7.9

### Description

When performing nucleus segmentation on image tiles, vertical strips of regions across the images did not get segmented.

### What I Did

I followed the code snippets in the tutorial jupyter notebook to perform inference on a stain normalized image. However, when visualizing the results using the samplee code snippets, I noticed that a vertical region in the image (see attached image) did not get segmented, while other regions worked fine. I don't believe I have included any code or settings to skip a region:

```
objInstSegmentor = NucleusInstanceSegmentor(
    pretrained_model='hovernet_fast-pannuke', 
    #pretrained_model='hovernet_fast-monusac', 
    #pretrained_model='hovernet_original-consep', 
    num_loader_workers=2, 
    num_postproc_workers=2, 
    batch_size=4, 
)

lstTileOutput = objInstSegmentor.predict(
    [strImgFullpath],
    save_dir=f'{strOutputPath}{strImgName}/',
    mode='tile',
    on_gpu=ON_GPU,
    crash_on_exception=True,
)
```

A crop of the resulting visualization below:

<img width="171" alt="image" src="https://user-images.githubusercontent.com/8196285/193114998-2f0d11d5-4a98-4597-a5d8-1083af25100c.png">

Out of the 10 image tiles I tried, I see this phenomenon in 5 of them (50%). Please help. Apart from this issue the toolbox works great! Thanks!

Caleb

**Comment by shaneahmed** [comment]
Thanks Caleb for reporting this issue.

@adamshephard is this the bug you fixed in #430?

**Comment by adamshephard** [comment]
Hi Caleb and Shan,

Yes, I believe this is an issue that arose on the NucleusInstanceSegmenter as a result of the width and height arguments being the wrong way round. This was indeed solved in #430 in June. But it is not solved in the currently available versions of TIAToolbox with pypi and conda etc.

Caleb, if you pull the current 'develop' version of TIAToolbox this should be solved. Alternatively, feel free to change the incorrect lines in your local version of the toolbox, as seen in the below commit:
https://github.com/TissueImageAnalytics/tiatoolbox/commit/ba8e2dc601082a2dc39c745836620b746eea9749

Hope this solves your issue.

Best,
Adam

**Comment by shaneahmed** [comment]
Closing this issue for now.
@Calebium Please feel free to open this issue if the above fix does not resolve #482.
